//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DemoProto.proto
// Note: requires additional types generated from: GameEnum.proto
namespace ProtoBufSpace
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegistReq")]
  public partial class RegistReq : global::ProtoBuf.IExtensible
  {
    public RegistReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Registres")]
  public partial class Registres : global::ProtoBuf.IExtensible
  {
    public Registres() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Loginres")]
  public partial class Loginres : global::ProtoBuf.IExtensible
  {
    public Loginres() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTableReq")]
  public partial class CreateTableReq : global::ProtoBuf.IExtensible
  {
    public CreateTableReq() {}
    
    private uint _maxNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateTableres")]
  public partial class CreateTableres : global::ProtoBuf.IExtensible
  {
    public CreateTableres() {}
    
    private uint _maxNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameTablePush")]
  public partial class GameTablePush : global::ProtoBuf.IExtensible
  {
    public GameTablePush() {}
    
    private readonly global::System.Collections.Generic.List<GameTableMsg> _gameTableMsgList = new global::System.Collections.Generic.List<GameTableMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gameTableMsgList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameTableMsg> gameTableMsgList
    {
      get { return _gameTableMsgList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameTableMsg")]
  public partial class GameTableMsg : global::ProtoBuf.IExtensible
  {
    public GameTableMsg() {}
    
    private uint _maxNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _memberList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"memberList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> memberList
    {
      get { return _memberList; }
    }
  
    private string _roomName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameIdentityConfirmPush")]
  public partial class GameIdentityConfirmPush : global::ProtoBuf.IExtensible
  {
    public GameIdentityConfirmPush() {}
    
    private readonly global::System.Collections.Generic.List<long> _evildoerList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"evildoerList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> evildoerList
    {
      get { return _evildoerList; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _merlinList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"merlinList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> merlinList
    {
      get { return _merlinList; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _mutualEvildoerList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"mutualEvildoerList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> mutualEvildoerList
    {
      get { return _mutualEvildoerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterTableReq")]
  public partial class EnterTableReq : global::ProtoBuf.IExtensible
  {
    public EnterTableReq() {}
    
    private string _roomName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterTableres")]
  public partial class EnterTableres : global::ProtoBuf.IExtensible
  {
    public EnterTableres() {}
    
    private GameTableMsg _tableMsg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tableMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameTableMsg tableMsg
    {
      get { return _tableMsg; }
      set { _tableMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTablePush")]
  public partial class UpdateTablePush : global::ProtoBuf.IExtensible
  {
    public UpdateTablePush() {}
    
    private GameTableMsg _tableMsg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tableMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public GameTableMsg tableMsg
    {
      get { return _tableMsg; }
      set { _tableMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuitTableReq")]
  public partial class QuitTableReq : global::ProtoBuf.IExtensible
  {
    public QuitTableReq() {}
    
    private uint _tableID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tableID
    {
      get { return _tableID; }
      set { _tableID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuitTableres")]
  public partial class QuitTableres : global::ProtoBuf.IExtensible
  {
    public QuitTableres() {}
    
    private readonly global::System.Collections.Generic.List<GameTableMsg> _gameTableMsgList = new global::System.Collections.Generic.List<GameTableMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gameTableMsgList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GameTableMsg> gameTableMsgList
    {
      get { return _gameTableMsgList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameInitPush")]
  public partial class GameInitPush : global::ProtoBuf.IExtensible
  {
    public GameInitPush() {}
    
    private GameIdentity _identity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"identity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameIdentity identity
    {
      get { return _identity; }
      set { _identity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameIdentityConfirmReq")]
  public partial class GameIdentityConfirmReq : global::ProtoBuf.IExtensible
  {
    public GameIdentityConfirmReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStartSendCardPush")]
  public partial class GameStartSendCardPush : global::ProtoBuf.IExtensible
  {
    public GameStartSendCardPush() {}
    
    private uint _roundIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundIndex
    {
      get { return _roundIndex; }
      set { _roundIndex = value; }
    }
    private uint _lapValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lapValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lapValue
    {
      get { return _lapValue; }
      set { _lapValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameSendCardReq")]
  public partial class GameSendCardReq : global::ProtoBuf.IExtensible
  {
    public GameSendCardReq() {}
    
    private readonly global::System.Collections.Generic.List<uint> _getCardList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"getCardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> getCardList
    {
      get { return _getCardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameGetCardPush")]
  public partial class GameGetCardPush : global::ProtoBuf.IExtensible
  {
    public GameGetCardPush() {}
    
    private readonly global::System.Collections.Generic.List<uint> _getCardList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"getCardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> getCardList
    {
      get { return _getCardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameSpeakPush")]
  public partial class GameSpeakPush : global::ProtoBuf.IExtensible
  {
    public GameSpeakPush() {}
    
    private uint _roundIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundIndex
    {
      get { return _roundIndex; }
      set { _roundIndex = value; }
    }
    private uint _lapValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lapValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lapValue
    {
      get { return _lapValue; }
      set { _lapValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameSpeakReq")]
  public partial class GameSpeakReq : global::ProtoBuf.IExtensible
  {
    public GameSpeakReq() {}
    
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameSpeakEndReq")]
  public partial class GameSpeakEndReq : global::ProtoBuf.IExtensible
  {
    public GameSpeakEndReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartLapSummaryPush")]
  public partial class StartLapSummaryPush : global::ProtoBuf.IExtensible
  {
    public StartLapSummaryPush() {}
    
    private uint _roundIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundIndex
    {
      get { return _roundIndex; }
      set { _roundIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeSendCardReq")]
  public partial class ChangeSendCardReq : global::ProtoBuf.IExtensible
  {
    public ChangeSendCardReq() {}
    
    private readonly global::System.Collections.Generic.List<uint> _getCardList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"getCardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> getCardList
    {
      get { return _getCardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndLapSummaryReq")]
  public partial class EndLapSummaryReq : global::ProtoBuf.IExtensible
  {
    public EndLapSummaryReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectTaskCardPush")]
  public partial class SelectTaskCardPush : global::ProtoBuf.IExtensible
  {
    public SelectTaskCardPush() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskCardReq")]
  public partial class TaskCardReq : global::ProtoBuf.IExtensible
  {
    public TaskCardReq() {}
    
    private bool _taskValueSign;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskValueSign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool taskValueSign
    {
      get { return _taskValueSign; }
      set { _taskValueSign = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskresultPush")]
  public partial class TaskresultPush : global::ProtoBuf.IExtensible
  {
    public TaskresultPush() {}
    
    private uint _roundIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundIndex
    {
      get { return _roundIndex; }
      set { _roundIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<bool> _resultList = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(2, Name=@"resultList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> resultList
    {
      get { return _resultList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartAssassinatePush")]
  public partial class StartAssassinatePush : global::ProtoBuf.IExtensible
  {
    public StartAssassinatePush() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssassinateReq")]
  public partial class AssassinateReq : global::ProtoBuf.IExtensible
  {
    public AssassinateReq() {}
    
    private uint _targetID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint targetID
    {
      get { return _targetID; }
      set { _targetID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameOVerPush")]
  public partial class GameOVerPush : global::ProtoBuf.IExtensible
  {
    public GameOVerPush() {}
    
    private GameOverType _gameOverType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameOverType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GameOverType gameOverType
    {
      get { return _gameOverType; }
      set { _gameOverType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}