//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameEnum.proto
namespace ProtoBufSpace
{
    [global::ProtoBuf.ProtoContract(Name=@"GameIdentity")]
    public enum GameIdentity
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Merlin", Value=1)]
      Merlin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Percival", Value=3)]
      Percival = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Loyal", Value=5)]
      Loyal = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Mordred", Value=2)]
      Mordred = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Morgana", Value=4)]
      Morgana = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Assassin", Value=6)]
      Assassin = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Oberon", Value=8)]
      Oberon = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Lackey", Value=9)]
      Lackey = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameOverType")]
    public enum GameOverType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskSucceed", Value=1)]
      TaskSucceed = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MerlinDie", Value=2)]
      MerlinDie = 2
    }
  
}