//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoEnum.proto
namespace ProtoBufSpace
{
    [global::ProtoBuf.ProtoContract(Name=@"TProtocol")]
    public enum TProtocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login_Req", Value=1)]
      Login_Req = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login_res", Value=2)]
      Login_res = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regist_Req", Value=3)]
      Regist_Req = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regist_res", Value=4)]
      Regist_res = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateTable_Req", Value=5)]
      CreateTable_Req = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateTable_res", Value=6)]
      CreateTable_res = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameTable_Push", Value=108)]
      GameTable_Push = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameIdentityConfirm_Push", Value=110)]
      GameIdentityConfirm_Push = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterTable_Req", Value=11)]
      EnterTable_Req = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterTable_res", Value=12)]
      EnterTable_res = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UpdateTable_Push", Value=114)]
      UpdateTable_Push = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuitTable_Req", Value=15)]
      QuitTable_Req = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuitTable_res", Value=16)]
      QuitTable_res = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameInit_Push", Value=118)]
      GameInit_Push = 118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameIdentityConfirm_Req", Value=19)]
      GameIdentityConfirm_Req = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameStartSendCard_Push", Value=122)]
      GameStartSendCard_Push = 122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameSendCard_Req", Value=23)]
      GameSendCard_Req = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameGetCard_Push", Value=124)]
      GameGetCard_Push = 124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameSpeak_Push", Value=126)]
      GameSpeak_Push = 126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameSpeak_Req", Value=27)]
      GameSpeak_Req = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameSpeakEnd_Req", Value=29)]
      GameSpeakEnd_Req = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartLapSummary_Push", Value=130)]
      StartLapSummary_Push = 130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeSendCard_Req", Value=31)]
      ChangeSendCard_Req = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndLapSummary_Req", Value=33)]
      EndLapSummary_Req = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SelectTaskCard_Push", Value=134)]
      SelectTaskCard_Push = 134,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TaskCard_Req", Value=35)]
      TaskCard_Req = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Taskresult_Push", Value=138)]
      Taskresult_Push = 138,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartAssassinate_Push", Value=140)]
      StartAssassinate_Push = 140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Assassinate_Req", Value=41)]
      Assassinate_Req = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOVer_Push", Value=144)]
      GameOVer_Push = 144
    }
  
}