//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ReturnCode.proto
namespace ProtoBufSpace
{
    [global::ProtoBuf.ProtoContract(Name=@"ReturnCode")]
    public enum ReturnCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=1)]
      Success = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login_Pwd_Error", Value=2)]
      Login_Pwd_Error = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regist_Account_Repeat", Value=3)]
      Regist_Account_Repeat = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regist_Account_Format_Error", Value=4)]
      Regist_Account_Format_Error = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Regist_Pwd_Format_Error", Value=5)]
      Regist_Pwd_Format_Error = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login_Account_not_exist", Value=6)]
      Login_Account_not_exist = 6
    }
  
}